language: node_js

node_js:
  - "8"

before_script:
- export TZ=America/New_York

script:
- npm run build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: storybook
  local_dir: storybook-static
