name: Test Circulation-Web
on:
  [push, pull_request]

jobs:
  test-circulation-web:
    name: Run Circulation-Web Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v2
     
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
        # node 10 is the node used in the docker image for circulation
          node-version: '10.x'
      
      - name: Install dependencies
        run: npm ci
     
      - name: Run tests
        env:
          TZ: America/New_York
        run: npm test